-- Basic
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')

-- Plugins
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
require('plugins.nulls')
require('plugins.autopairs')
require('plugins.autotag')
require('plugins.bufferline')
require('plugins.comments')
require('plugins.gitsigns')
require('plugins.lualine') 
require('plugins.toggleterm')
require('plugins.whichkey')
